export const LABELS_CARACTERISTICAS: Record<string, string> = {
  setor: 'Setor',
  qtdColaboradores: 'Quantidade de Colaboradores',
  dimensoes: 'Dimensões',
  peDireito: 'Pé-direito',
  pavimento: 'Pavimento',
  paredesVedacao: 'Paredes/Vedação',
  divisoria: 'Divisória',
  piso: 'Piso',
  revestimento: 'Revestimento',
  forro: 'Forro',
  telhado: 'Telhado',
  iluminacaoNatural: 'Iluminação Natural',
  iluminacaoArtificial: 'Iluminação Artificial',
  ventilacaoNatural: 'Ventilação Natural',
  ventilacaoArtificial: 'Ventilação Artificial',
  sistemaIncendio: 'Sistema de Incêndio',
  possibilidadeGES: 'Possibilidade de GES',
  mobiliarios: 'Mobiliários',
  maquinasEquipamentos: 'Máquinas e Equipamentos',
  epis: 'EPIs',
  epcs: 'EPCs',
  imagens: 'Imagens',
}
